
services:
  # Сервис 1: Игровой сервер Obsidian Conflict (Windows-версия на Linux через Wine)
  game-server:
    image: ich777/steamcmd:latest
    container_name: oc_game_server
    volumes:
      # Постоянное хранилище для файлов игры на жестком диске Linux-сервера
      - ./server_data:/serverdata/serverfiles
      - ./server/server.cfg:/serverdata/serverfiles/obsidian/cfg/server.cfg
    ports:
      - "27015:27015/udp" # Игровой трафик
      - "27015:27015/tcp" # RCON трафик
    environment:
      - RCON_PASSWORD=${RCON_PASSWORD}
      - GAME_ID=244300      # AppID для Source SDK Base 2013 Dedicated Server
      - GAME_NAME=obsidian
      - USERNAME=blank     # По документации образа: 'blank' для анонимного входа
      - PASSWRD=blank      # По документации образа: 'blank' для анонимного входа
      # Параметры запуска передаем через GAME_PARAMS (без дублирования -game и -port)
      - GAME_PARAMS=-console +map oc_harvest +maxplayers 8 +rcon_password ${RCON_PASSWORD} -noscripting
    restart: unless-stopped

  # Сервис 2: Наш Discord-бот
  discord-bot:
    build: ./bot
    container_name: oc_discord_bot
    depends_on:
      - game-server
    environment:
      - SERVER_IP=game-server 
      - RCON_PORT=27015
      - RCON_PASSWORD=${RCON_PASSWORD}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SERVER_REAL_IP=${SERVER_IP}
      - NOTIFY_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    restart: unless-stopped

  # Сервис 3: Быстрая загрузка файлов для игроков (FastDL)
  fastdl-web:
    image: nginx:alpine
    container_name: oc_fastdl
    volumes:
      # Делимся файлами карт и моделей из игрового сервера с веб-сервером
      - ./server_data/obsidian:/usr/share/nginx/html/obsidian:ro
    ports:
      - "80:80" # Открываем стандартный веб-порт
    restart: unless-stopped

  # Сервис 4: Сервер интернет-радио для синхронизации музыки
  icecast-stream:
    image: infiniteproject/icecast:latest
    container_name: oc_icecast
    ports:
      - "8000:8000" # Порт радиопотока
    environment:
      - ICECAST_SOURCE_PASSWORD=hackme_source
      - ICECAST_ADMIN_PASSWORD=hackme_admin
      - ICECAST_PASSWORD=hackme_relay
    restart: unless-stopped
